### ISSUE TITLE
What is the cut-off value should I use?

### ISSUE THREAD

**Issue by jsonProgram** [xjtu-omics/msisensor-pro#4]
hi Jia,

Is it as same as msisensor2? cut-off value =20?

and,
for different sample  type should have the different cut-off value ?

Json

**Comment by PengJia6** [comment]
> hi Jia,
> 
> Is it as same as msisensor2? cut-off value =20?
> 
> and,
> for different sample type should have the different cut-off value ?
> 
> Json

Hi Json,

MSIsensor-pro and MSIsensor2 are two different software for MSI calling. In MSIsensor-pro, we did not provide a cut-off, because the cut-off will be different for different sequencing panel. If you want to use MSIsensor-pro in a new panel for only tumor sample MSI detection, please use the msi status from msisensor or gold standard as true value to obtain a cut-off suit for your panel.

By the way, it seems that MSI is a continuous value, and you can just use msi score for you research.

Best,

Peng

**Comment by katecycho** [comment]
Do you have a recommendation of cut-off value for wgs??
