### ISSUE TITLE
bam file error when running  "msisensor-pro baseline"  step

### ISSUE THREAD

**Issue by YXbioinfor** [xjtu-omics/msisensor-pro#46]
Dear author ：
 i got a very strange  error  when i runing  
 `
 msisensor-pro baseline -d $ref_list/reference.list -i  configure.txt -o  ./
`
**Open bam file failed(  ), please provide valid bam file with its index file !**
it seem to say that  i have to  set index file for every bam file, so i use **samtools index** to do this then  i got .bai index files for every bam file.
then I repat the code agagin ,however the same error  happend
where i was wrong?!
thank you for your answer

**Comment by PengJia6** [comment]
Did you give correct path of the bam file?

**Comment by nservant** [comment]
Hi, I think I have the same issue, which is due to the fact that the code is using real path ...
For instance, if you put in the same folder two bam/bai using symbolic links, pointing to the files in different folder, MSIsensor is not able to match them. This is because MSIsensor consider the real path of the files.
