### ISSUE TITLE
A few questions about baseline making

### ISSUE THREAD

**Issue by RADIOMUMM** [xjtu-omics/msisensor-pro#52]
HI ！
   I'm a little confused about baseline making！
1.Where do the BAM files needed to create Baseline come from?
2.Does the data have to come from the sample itself?
3.As long as the reference uses the same, it can be used as a normal bam for baseline?    

Best
jennis

**Comment by PengJia6** [comment]
1. samples from the same sequencing solution, maybe from the same panels. It depends on your application. 
2. If you have both tumor and normal samples from an individual, you can use the msisensor **msi**. 
3.  The baseline is used to filter out the bias caused by the sequencing platform, wet lab excrement, genetic background, etc.
