### ISSUE TITLE
Matched vs tumor_only scores

### ISSUE THREAD

**Issue by bounlu** [xjtu-omics/msisensor-pro#65]
I have compared MSI scores for the same tumor samples between:

1. its matched normal (`msi`)
2. a baseline of normals (`pro`)

I had 65 tumor and 58 normal samples of which 55 are matched.

In case 1 above, I used 55 matched samples and run the analysis for each normal-tumor pair.

In case 2, I used all 58 normal samples to create a baseline and compared each of tumor samples to this baseline.

I used default values for all parameters.

Between the two analysis, I got very different results for the same tumor samples in terms of somatic sites / MSI scores.

Case 1 gave none to very few events, resulting in around 0% MSI.
Case 2 gave a range more than 1%, with a few samples up to 5-10% MSI.

How to explain this discrepancy? Which one to trust more?

**Comment by PengJia6** [comment]
Case 1 is more accurate because each sample in Case 1 uses its own corresponding control sample, whereas Case 2 uses a "bulk" baseline as the control.  And it is important to note that the values in the two cases do not directly correspond to MSI status. They should follow some kind of linear relationship.
